-- Migration: 092_asset_workbench_piecework_settlement.sql
-- Independent asset workbench for delivery item submission and piecework settlement.

CREATE TABLE IF NOT EXISTS asset_workbench_profiles (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  worker_type VARCHAR(32) NOT NULL DEFAULT '',
  job_grade VARCHAR(32) NOT NULL DEFAULT '',
  real_name VARCHAR(128) NOT NULL DEFAULT '',
  phone VARCHAR(64) NULL,
  province VARCHAR(64) NOT NULL DEFAULT '',
  city VARCHAR(64) NOT NULL DEFAULT '',
  id_card VARCHAR(64) NULL,
  gender VARCHAR(32) NOT NULL DEFAULT '',
  alipay_account VARCHAR(128) NOT NULL DEFAULT '',
  onboarded_at DATETIME NULL,
  grade_hidden TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  pii_completed TINYINT(1) NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_profiles_user (user_id),
  UNIQUE KEY uk_aw_profiles_phone (phone),
  UNIQUE KEY uk_aw_profiles_id_card (id_card),
  KEY idx_aw_profiles_worker_grade (worker_type, job_grade),
  KEY idx_aw_profiles_status (status),
  CONSTRAINT fk_aw_profiles_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_profile_grade_periods (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  profile_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  worker_type VARCHAR(32) NOT NULL,
  job_grade VARCHAR(32) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NULL,
  changed_by BIGINT NULL,
  reason VARCHAR(512) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_aw_grade_periods_profile (profile_id, effective_from),
  KEY idx_aw_grade_periods_user_month (user_id, effective_from, effective_to),
  CONSTRAINT fk_aw_grade_periods_profile FOREIGN KEY (profile_id) REFERENCES asset_workbench_profiles(id),
  CONSTRAINT fk_aw_grade_periods_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_settlement_batches (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  batch_no VARCHAR(64) NOT NULL,
  business_month CHAR(7) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'generated',
  generated_by BIGINT NOT NULL,
  confirmed_by BIGINT NULL,
  cancelled_by BIGINT NULL,
  generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmed_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  cancel_reason VARCHAR(512) NOT NULL DEFAULT '',
  item_count INT NOT NULL DEFAULT 0,
  gross_amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  deduction_amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  welfare_amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  supplement_amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  adjustment_amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  net_amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_settlement_batches_no (batch_no),
  KEY idx_aw_settlement_batches_month_status (business_month, status),
  KEY idx_aw_settlement_batches_generated_by (generated_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_upload_sessions (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  session_id CHAR(36) NOT NULL,
  owner_user_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'created',
  object_key VARCHAR(512) NOT NULL DEFAULT '',
  original_filename VARCHAR(255) NOT NULL DEFAULT '',
  file_size BIGINT NOT NULL DEFAULT 0,
  mime_type VARCHAR(128) NOT NULL DEFAULT '',
  file_hash VARCHAR(128) NOT NULL DEFAULT '',
  upload_id VARCHAR(255) NOT NULL DEFAULT '',
  multipart_plan_json JSON NULL,
  expires_at DATETIME NOT NULL,
  uploaded_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  submitted_item_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_upload_sessions_session (session_id),
  KEY idx_aw_upload_sessions_owner_status (owner_user_id, status),
  KEY idx_aw_upload_sessions_expiry (status, expires_at),
  KEY idx_aw_upload_sessions_hash (file_hash),
  CONSTRAINT fk_aw_upload_sessions_owner FOREIGN KEY (owner_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_submissions (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  submission_no VARCHAR(64) NOT NULL,
  submitter_user_id BIGINT NOT NULL,
  business_month CHAR(7) NOT NULL,
  submitted_at DATETIME NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'submitted',
  item_count INT NOT NULL DEFAULT 0,
  file_count INT NOT NULL DEFAULT 0,
  page_count INT NOT NULL DEFAULT 0,
  gross_total DECIMAL(14,4) NOT NULL DEFAULT 0,
  notes VARCHAR(1024) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_submissions_no (submission_no),
  KEY idx_aw_submissions_submitter_month (submitter_user_id, business_month),
  KEY idx_aw_submissions_status_month (status, business_month),
  CONSTRAINT fk_aw_submissions_submitter FOREIGN KEY (submitter_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_submission_items (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  submission_id BIGINT NOT NULL,
  payee_user_id BIGINT NOT NULL,
  order_no VARCHAR(128) NOT NULL,
  difficulty_class VARCHAR(64) NOT NULL,
  finalized TINYINT(1) NOT NULL DEFAULT 0,
  page_count INT NOT NULL DEFAULT 1,
  item_count INT NOT NULL DEFAULT 1,
  business_month CHAR(7) NOT NULL,
  submitted_at DATETIME NOT NULL,
  worker_type_snapshot VARCHAR(32) NOT NULL DEFAULT '',
  job_grade_snapshot VARCHAR(32) NOT NULL DEFAULT '',
  base_price_rule_id BIGINT NULL,
  base_unit_price DECIMAL(14,4) NULL,
  promo_coupon_id BIGINT NULL,
  promo_snapshot_json JSON NULL,
  pricing_snapshot_json JSON NULL,
  gross_amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  pricing_status VARCHAR(32) NOT NULL DEFAULT 'unpriced',
  qc_status VARCHAR(32) NOT NULL DEFAULT 'submitted',
  settlement_status VARCHAR(32) NOT NULL DEFAULT 'unsettled',
  current_settlement_batch_id BIGINT NULL,
  voided_at DATETIME NULL,
  voided_by BIGINT NULL,
  void_reason VARCHAR(512) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aw_items_submission (submission_id),
  KEY idx_aw_items_payee_month (payee_user_id, business_month),
  KEY idx_aw_items_order_no (order_no),
  KEY idx_aw_items_pricing_status (pricing_status),
  KEY idx_aw_items_qc_status (qc_status),
  KEY idx_aw_items_settlement (settlement_status, current_settlement_batch_id),
  KEY idx_aw_items_current_batch (current_settlement_batch_id),
  CONSTRAINT fk_aw_items_submission FOREIGN KEY (submission_id) REFERENCES asset_workbench_submissions(id),
  CONSTRAINT fk_aw_items_payee FOREIGN KEY (payee_user_id) REFERENCES users(id),
  CONSTRAINT fk_aw_items_current_batch FOREIGN KEY (current_settlement_batch_id) REFERENCES asset_workbench_settlement_batches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_submission_files (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  submission_id BIGINT NOT NULL,
  submission_item_id BIGINT NOT NULL,
  upload_session_id BIGINT NULL,
  owner_user_id BIGINT NOT NULL,
  object_key VARCHAR(512) NOT NULL,
  preview_key VARCHAR(512) NOT NULL DEFAULT '',
  preview_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  preview_attempts INT NOT NULL DEFAULT 0,
  preview_error VARCHAR(1024) NOT NULL DEFAULT '',
  preview_next_retry_at DATETIME NULL,
  preview_worker_id VARCHAR(128) NOT NULL DEFAULT '',
  preview_lease_expires_at DATETIME NULL,
  original_filename VARCHAR(255) NOT NULL,
  file_ext VARCHAR(32) NOT NULL DEFAULT '',
  file_type VARCHAR(64) NOT NULL DEFAULT '',
  mime_type VARCHAR(128) NOT NULL DEFAULT '',
  file_size BIGINT NOT NULL DEFAULT 0,
  file_hash VARCHAR(128) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aw_files_submission (submission_id),
  KEY idx_aw_files_item (submission_item_id),
  KEY idx_aw_files_preview_queue (preview_status, preview_next_retry_at, preview_lease_expires_at),
  KEY idx_aw_files_hash (file_hash),
  CONSTRAINT fk_aw_files_submission FOREIGN KEY (submission_id) REFERENCES asset_workbench_submissions(id),
  CONSTRAINT fk_aw_files_item FOREIGN KEY (submission_item_id) REFERENCES asset_workbench_submission_items(id),
  CONSTRAINT fk_aw_files_upload_session FOREIGN KEY (upload_session_id) REFERENCES asset_workbench_upload_sessions(id),
  CONSTRAINT fk_aw_files_owner FOREIGN KEY (owner_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_price_matrix_dimensions (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  worker_type VARCHAR(32) NOT NULL,
  job_grade VARCHAR(32) NOT NULL,
  difficulty_class VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_price_dimension (worker_type, job_grade, difficulty_class)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_price_matrix (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  worker_type VARCHAR(32) NOT NULL,
  job_grade VARCHAR(32) NOT NULL,
  difficulty_class VARCHAR(64) NOT NULL,
  unit_price DECIMAL(14,4) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  revision_no INT NOT NULL DEFAULT 1,
  created_by BIGINT NOT NULL,
  remark VARCHAR(512) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aw_price_lookup (worker_type, job_grade, difficulty_class, enabled, effective_from, effective_to),
  KEY idx_aw_price_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_deduction_rules (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  worker_type VARCHAR(32) NOT NULL DEFAULT 'all',
  job_grade VARCHAR(32) NOT NULL DEFAULT 'all',
  difficulty_class VARCHAR(64) NOT NULL,
  deduction_amount DECIMAL(14,4) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  revision_no INT NOT NULL DEFAULT 1,
  created_by BIGINT NOT NULL,
  remark VARCHAR(512) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aw_deduction_lookup (worker_type, job_grade, difficulty_class, enabled, effective_from, effective_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_welfare_rules (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  rule_name VARCHAR(128) NOT NULL,
  worker_type VARCHAR(32) NOT NULL DEFAULT 'all',
  job_grade VARCHAR(32) NOT NULL DEFAULT 'all',
  rule_type VARCHAR(64) NOT NULL DEFAULT 'manual',
  amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  config_json JSON NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT NOT NULL,
  remark VARCHAR(512) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aw_welfare_lookup (worker_type, job_grade, rule_type, enabled, effective_from, effective_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_promo_coupons (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  coupon_code VARCHAR(64) NOT NULL,
  coupon_name VARCHAR(128) NOT NULL,
  mode VARCHAR(32) NOT NULL,
  amount DECIMAL(14,4) NULL,
  percent DECIMAL(10,4) NULL,
  priority INT NOT NULL DEFAULT 100,
  worker_type VARCHAR(32) NOT NULL DEFAULT 'all',
  job_grade VARCHAR(32) NOT NULL DEFAULT 'all',
  difficulty_class VARCHAR(64) NOT NULL DEFAULT 'all',
  eligible_user_ids_json JSON NULL,
  eligible_codes_json JSON NULL,
  effective_from DATETIME NOT NULL,
  effective_to DATETIME NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  stack_policy VARCHAR(32) NOT NULL DEFAULT 'single_winner',
  created_by BIGINT NOT NULL,
  remark VARCHAR(512) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_promo_code (coupon_code),
  KEY idx_aw_promo_lookup (enabled, effective_from, effective_to, priority),
  KEY idx_aw_promo_dimension (worker_type, job_grade, difficulty_class)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_error_import_batches (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  import_no VARCHAR(64) NOT NULL,
  business_month CHAR(7) NOT NULL,
  uploaded_by BIGINT NOT NULL,
  original_filename VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'imported',
  total_rows INT NOT NULL DEFAULT 0,
  matched_rows INT NOT NULL DEFAULT 0,
  unmatched_rows INT NOT NULL DEFAULT 0,
  ambiguous_rows INT NOT NULL DEFAULT 0,
  error_message VARCHAR(1024) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_error_import_no (import_no),
  KEY idx_aw_error_import_month_status (business_month, status),
  CONSTRAINT fk_aw_error_import_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_error_records (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  import_batch_id BIGINT NOT NULL,
  business_month CHAR(7) NOT NULL,
  payee_user_id BIGINT NULL,
  order_no VARCHAR(128) NOT NULL,
  error_count INT NOT NULL DEFAULT 0,
  raw_payload_json JSON NULL,
  match_status VARCHAR(32) NOT NULL DEFAULT 'unmatched',
  submission_item_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aw_error_records_order_month (order_no, business_month),
  KEY idx_aw_error_records_payee_month (payee_user_id, business_month),
  KEY idx_aw_error_records_item (submission_item_id),
  CONSTRAINT fk_aw_error_records_batch FOREIGN KEY (import_batch_id) REFERENCES asset_workbench_error_import_batches(id),
  CONSTRAINT fk_aw_error_records_payee FOREIGN KEY (payee_user_id) REFERENCES users(id),
  CONSTRAINT fk_aw_error_records_item FOREIGN KEY (submission_item_id) REFERENCES asset_workbench_submission_items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_settlement_items (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  batch_id BIGINT NOT NULL,
  item_type VARCHAR(32) NOT NULL,
  submission_item_id BIGINT NULL,
  payee_user_id BIGINT NOT NULL,
  business_month CHAR(7) NOT NULL,
  amount DECIMAL(14,4) NOT NULL,
  quantity DECIMAL(14,4) NOT NULL DEFAULT 1,
  unit_price DECIMAL(14,4) NULL,
  direction VARCHAR(16) NOT NULL DEFAULT 'credit',
  source_ref_type VARCHAR(64) NOT NULL DEFAULT '',
  source_ref_id BIGINT NULL,
  snapshot_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_aw_settlement_items_batch (batch_id),
  KEY idx_aw_settlement_items_payee_month (payee_user_id, business_month),
  KEY idx_aw_settlement_items_submission_item (submission_item_id),
  KEY idx_aw_settlement_items_type (item_type),
  CONSTRAINT fk_aw_settlement_items_batch FOREIGN KEY (batch_id) REFERENCES asset_workbench_settlement_batches(id),
  CONSTRAINT fk_aw_settlement_items_submission_item FOREIGN KEY (submission_item_id) REFERENCES asset_workbench_submission_items(id),
  CONSTRAINT fk_aw_settlement_items_payee FOREIGN KEY (payee_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_settlement_adjustments (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  batch_id BIGINT NULL,
  payee_user_id BIGINT NOT NULL,
  business_month CHAR(7) NOT NULL,
  adjustment_type VARCHAR(32) NOT NULL DEFAULT 'adjustment',
  amount DECIMAL(14,4) NOT NULL,
  reason VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  payload_json JSON NULL,
  created_by BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aw_adjustments_batch (batch_id),
  KEY idx_aw_adjustments_payee_month (payee_user_id, business_month),
  CONSTRAINT fk_aw_adjustments_batch FOREIGN KEY (batch_id) REFERENCES asset_workbench_settlement_batches(id),
  CONSTRAINT fk_aw_adjustments_payee FOREIGN KEY (payee_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_supplement_permissions (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  payee_user_id BIGINT NOT NULL,
  business_month CHAR(7) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  reason VARCHAR(512) NOT NULL DEFAULT '',
  granted_by BIGINT NOT NULL,
  revoked_by BIGINT NULL,
  granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_supplement_permissions_user_month (payee_user_id, business_month),
  KEY idx_aw_supplement_permissions_month_enabled (business_month, enabled),
  CONSTRAINT fk_aw_supplement_permissions_payee FOREIGN KEY (payee_user_id) REFERENCES users(id),
  CONSTRAINT fk_aw_supplement_permissions_granted_by FOREIGN KEY (granted_by) REFERENCES users(id),
  CONSTRAINT fk_aw_supplement_permissions_revoked_by FOREIGN KEY (revoked_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_settlement_supplements (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  payee_user_id BIGINT NOT NULL,
  business_month CHAR(7) NOT NULL,
  linked_batch_id BIGINT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  order_no VARCHAR(128) NOT NULL,
  difficulty_class VARCHAR(64) NOT NULL,
  finalized TINYINT(1) NOT NULL DEFAULT 0,
  page_count INT NOT NULL DEFAULT 1,
  gross_amount DECIMAL(14,4) NOT NULL DEFAULT 0,
  duplicate_hint_json JSON NULL,
  created_by BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aw_supplements_payee_month (payee_user_id, business_month),
  KEY idx_aw_supplements_order (order_no, business_month),
  KEY idx_aw_supplements_status (status),
  CONSTRAINT fk_aw_supplements_payee FOREIGN KEY (payee_user_id) REFERENCES users(id),
  CONSTRAINT fk_aw_supplements_batch FOREIGN KEY (linked_batch_id) REFERENCES asset_workbench_settlement_batches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_events (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  actor_user_id BIGINT NULL,
  event_type VARCHAR(64) NOT NULL,
  entity_type VARCHAR(64) NOT NULL,
  entity_id BIGINT NULL,
  before_json JSON NULL,
  after_json JSON NULL,
  reason VARCHAR(512) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_aw_events_entity (entity_type, entity_id, created_at),
  KEY idx_aw_events_actor (actor_user_id, created_at),
  KEY idx_aw_events_type (event_type, created_at),
  CONSTRAINT fk_aw_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_workbench_saved_views (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  view_type VARCHAR(64) NOT NULL,
  view_name VARCHAR(128) NOT NULL,
  config_json JSON NOT NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_aw_saved_views_name (user_id, view_type, view_name),
  KEY idx_aw_saved_views_user_type (user_id, view_type),
  CONSTRAINT fk_aw_saved_views_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
