CREATE TABLE IF NOT EXISTS cost_recalculation_runs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  run_no VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  mode VARCHAR(32) NOT NULL,
  filters_json LONGTEXT NULL,
  summary_json LONGTEXT NULL,
  item_count INT NOT NULL DEFAULT 0,
  created_by BIGINT NOT NULL DEFAULT 0,
  applied_by BIGINT NULL,
  erp_synced_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  previewed_at TIMESTAMP NULL,
  applied_at TIMESTAMP NULL,
  erp_synced_at TIMESTAMP NULL,
  cancelled_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_cost_recalc_runs_no (run_no),
  KEY idx_cost_recalc_runs_status (status),
  KEY idx_cost_recalc_runs_created_by (created_by, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cost_recalculation_run_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  run_id BIGINT NOT NULL,
  product_management_record_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  task_no VARCHAR(64) NOT NULL DEFAULT '',
  task_sku_item_id BIGINT NULL,
  sku_code VARCHAR(128) NOT NULL DEFAULT '',
  erp_i_id VARCHAR(128) NOT NULL DEFAULT '',
  product_i_id VARCHAR(128) NOT NULL DEFAULT '',
  normalized_i_id VARCHAR(128) NOT NULL DEFAULT '',
  old_cost_price DECIMAL(12,3) NULL,
  new_cost_price DECIMAL(12,3) NULL,
  cost_delta DECIMAL(12,3) NULL,
  old_rule_id BIGINT NULL,
  new_rule_id BIGINT NULL,
  new_rule_version INT NULL,
  match_mode VARCHAR(32) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL,
  skip_reason VARCHAR(255) NOT NULL DEFAULT '',
  conflict_reason VARCHAR(255) NOT NULL DEFAULT '',
  preview_snapshot_json LONGTEXT NULL,
  apply_snapshot_json LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_cost_recalc_run_items_record (run_id, product_management_record_id),
  KEY idx_cost_recalc_run_items_status (run_id, status),
  KEY idx_cost_recalc_run_items_record_open (product_management_record_id, status),
  CONSTRAINT fk_cost_recalc_run_items_run
    FOREIGN KEY (run_id) REFERENCES cost_recalculation_runs(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
