package service

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"

	"workflow/domain"
	"workflow/repo"
)

const (
	createTaskBatchSKUModeSingle   = "single"
	createTaskBatchSKUModeMultiple = "multiple"
	maxBatchSKUGenerateAttempts    = 8
)

type taskBatchItemBuild struct {
	Item             *domain.TaskSKUItem
	AutoGeneratedSKU bool
}

func normalizeCreateTaskRequest(p CreateTaskParams) CreateTaskParams {
	p = normalizeCreateTaskParams(p)
	mode := strings.ToLower(strings.TrimSpace(p.BatchSKUMode))
	if mode == "" {
		mode = createTaskBatchSKUModeSingle
	}
	p.BatchSKUMode = mode
	if mode != createTaskBatchSKUModeMultiple && strings.TrimSpace(p.SKUCode) == "" {
		p.SKUCode = strings.TrimSpace(firstNonEmptyString(
			p.SKUCode,
			p.TopLevelNewSKU,
			p.TopLevelPurchaseSKU,
			p.PurchaseSKU,
		))
	}
	p.TopLevelNewSKU = strings.TrimSpace(p.TopLevelNewSKU)
	p.TopLevelPurchaseSKU = strings.TrimSpace(p.TopLevelPurchaseSKU)
	for i := range p.BatchItems {
		p.BatchItems[i].ProductName = strings.TrimSpace(p.BatchItems[i].ProductName)
		p.BatchItems[i].ProductShortName = strings.TrimSpace(p.BatchItems[i].ProductShortName)
		p.BatchItems[i].CategoryCode = strings.TrimSpace(p.BatchItems[i].CategoryCode)
		p.BatchItems[i].ProductIID = strings.TrimSpace(p.BatchItems[i].ProductIID)
		p.BatchItems[i].MaterialMode = strings.TrimSpace(p.BatchItems[i].MaterialMode)
		p.BatchItems[i].DesignRequirement = strings.TrimSpace(p.BatchItems[i].DesignRequirement)
		p.BatchItems[i].NewSKU = strings.TrimSpace(p.BatchItems[i].NewSKU)
		p.BatchItems[i].PurchaseSKU = strings.TrimSpace(p.BatchItems[i].PurchaseSKU)
		p.BatchItems[i].CostPriceMode = strings.TrimSpace(p.BatchItems[i].CostPriceMode)
		if len(p.BatchItems[i].VariantJSON) > 0 {
			p.BatchItems[i].VariantJSON = bytes.TrimSpace(p.BatchItems[i].VariantJSON)
		}
	}
	return p
}

func isMultipleBatchTaskRequest(p CreateTaskParams) bool {
	return strings.EqualFold(strings.TrimSpace(p.BatchSKUMode), createTaskBatchSKUModeMultiple)
}

// mergeBatchItemReferenceFileRefsIntoTask folds batch_items[].reference_file_refs into the top-level
// slice (deduped) so mother-task persistence and GET /v1/tasks/{id} stay aligned with single-task behavior.
func mergeBatchItemReferenceFileRefsIntoTask(p *CreateTaskParams) {
	if p == nil || !isMultipleBatchTaskRequest(*p) {
		return
	}
	n := len(p.ReferenceFileRefs)
	for _, item := range p.BatchItems {
		n += len(item.ReferenceFileRefs)
	}
	if n == 0 {
		return
	}
	merged := make([]domain.ReferenceFileRef, 0, n)
	merged = append(merged, p.ReferenceFileRefs...)
	for i := range p.BatchItems {
		merged = append(merged, p.BatchItems[i].ReferenceFileRefs...)
	}
	p.ReferenceFileRefs = domain.NormalizeReferenceFileRefs(merged)
}

func ValidateBatchTaskCreateRequest(p CreateTaskParams) *domain.AppError {
	if p.BatchSKUMode != "" &&
		p.BatchSKUMode != createTaskBatchSKUModeSingle &&
		p.BatchSKUMode != createTaskBatchSKUModeMultiple {
		return taskCreateValidationError(
			"batch_sku_mode must be single or multiple",
			p,
			taskCreateViolation("batch_sku_mode", "invalid_batch_sku_mode", "batch_sku_mode must be single or multiple"),
		)
	}

	var violations []map[string]interface{}
	addViolation := func(field, code, message string) {
		violations = append(violations, taskCreateViolation(field, code, message))
	}
	isMultiple := isMultipleBatchTaskRequest(p)

	if p.TaskType == domain.TaskTypeOriginalProductDevelopment {
		if isMultiple {
			addViolation("batch_sku_mode", "batch_not_supported_for_task_type", "original_product_development does not support batch_sku_mode=multiple")
		}
		if len(p.BatchItems) > 0 {
			addViolation("batch_items", "batch_not_supported_for_task_type", "original_product_development does not support batch_items")
		}
		if len(violations) > 0 {
			return taskCreateValidationError("batch task validation failed", p, violations...)
		}
		return nil
	}

	if !isMultiple {
		if len(p.BatchItems) > 0 {
			addViolation("batch_items", "batch_items_not_allowed", "batch_items is only allowed when batch_sku_mode=multiple")
		}
		if len(violations) > 0 {
			return taskCreateValidationError("batch task validation failed", p, violations...)
		}
		return nil
	}

	if len(p.BatchItems) < 2 {
		addViolation("batch_items", "insufficient_batch_items", "batch_items must contain at least 2 items when batch_sku_mode=multiple")
	}
	if p.SourceMode != domain.TaskSourceModeNewProduct {
		addViolation("source_mode", "invalid_source_mode_for_batch", "batch_sku_mode=multiple only supports source_mode=new_product")
	}
	if p.TaskType == domain.TaskTypeNewProductDevelopment && p.TopLevelNewSKU != "" {
		addViolation("new_sku", "top_level_single_sku_not_allowed", "top-level new_sku cannot be used when batch_sku_mode=multiple")
	}
	if p.TaskType == domain.TaskTypePurchaseTask && p.TopLevelPurchaseSKU != "" {
		addViolation("purchase_sku", "top_level_single_sku_not_allowed", "top-level purchase_sku cannot be used when batch_sku_mode=multiple")
	}
	if strings.TrimSpace(p.SKUCode) != "" {
		addViolation("sku_code", "top_level_single_sku_not_allowed", "top-level sku_code cannot be used when batch_sku_mode=multiple")
	}

	seenDedupe := map[string]int{}
	seenSKU := map[string]int{}
	for idx, item := range p.BatchItems {
		prefix := fmt.Sprintf("batch_items[%d]", idx)
		switch p.TaskType {
		case domain.TaskTypeNewProductDevelopment:
			if item.ProductName == "" {
				addViolation(prefix+".product_name", "missing_required_field", "batch_items[].product_name is required")
			}
			if item.MaterialMode != "" && !domain.MaterialMode(item.MaterialMode).Valid() {
				addViolation(prefix+".material_mode", "invalid_material_mode", "batch_items[].material_mode must be preset or other")
			}
			if item.DesignRequirement == "" {
				addViolation(prefix+".design_requirement", "missing_required_field", "batch_items[].design_requirement is required")
			}
			if item.PurchaseSKU != "" {
				addViolation(prefix+".purchase_sku", "field_not_allowed_for_task_type", "batch_items[].purchase_sku is not allowed for new_product_development")
			}
			if item.CostPriceMode != "" {
				addViolation(prefix+".cost_price_mode", "field_not_allowed_for_task_type", "batch_items[].cost_price_mode is not allowed for new_product_development")
			}
			if item.Quantity != nil {
				addViolation(prefix+".quantity", "field_not_allowed_for_task_type", "batch_items[].quantity is not allowed for new_product_development")
			}
			if item.BaseSalePrice != nil {
				addViolation(prefix+".base_sale_price", "field_not_allowed_for_task_type", "batch_items[].base_sale_price is not allowed for new_product_development")
			}
		case domain.TaskTypePurchaseTask:
			if item.ProductName == "" {
				addViolation(prefix+".product_name", "missing_required_field", "batch_items[].product_name is required")
			}
			if item.CategoryCode == "" {
				addViolation(prefix+".category_code", "missing_required_field", "batch_items[].category_code is required")
			}
			if item.CostPriceMode == "" {
				addViolation(prefix+".cost_price_mode", "missing_required_field", "batch_items[].cost_price_mode is required")
			} else if !domain.CostPriceMode(item.CostPriceMode).Valid() {
				addViolation(prefix+".cost_price_mode", "invalid_cost_price_mode", "batch_items[].cost_price_mode must be manual or template")
			}
			if item.Quantity == nil || *item.Quantity <= 0 {
				addViolation(prefix+".quantity", "missing_required_field", "batch_items[].quantity is required and must be greater than 0")
			}
			if item.BaseSalePrice == nil {
				addViolation(prefix+".base_sale_price", "missing_required_field", "batch_items[].base_sale_price is required")
			}
			if item.ProductShortName != "" {
				addViolation(prefix+".product_short_name", "field_not_allowed_for_task_type", "batch_items[].product_short_name is not allowed for purchase_task")
			}
			if item.MaterialMode != "" {
				addViolation(prefix+".material_mode", "field_not_allowed_for_task_type", "batch_items[].material_mode is not allowed for purchase_task")
			}
			if item.DesignRequirement != "" {
				addViolation(prefix+".design_requirement", "field_not_allowed_for_task_type", "batch_items[].design_requirement is not allowed for purchase_task")
			}
			if item.NewSKU != "" {
				addViolation(prefix+".new_sku", "field_not_allowed_for_task_type", "batch_items[].new_sku is not allowed for purchase_task")
			}
		}

		if _, appErr := normalizeVariantJSONForTaskBatchItem(item.VariantJSON); appErr != nil {
			addViolation(prefix+".variant_json", "invalid_variant_json", "batch_items[].variant_json must be valid JSON")
		}
		dedupeKey, appErr := computeTaskBatchItemDedupeKey(p.TaskType, item)
		if appErr != nil {
			addViolation(prefix+".variant_json", "invalid_variant_json", appErr.Message)
		} else if prev, ok := seenDedupe[dedupeKey]; ok {
			addViolation(prefix, "duplicate_batch_item", fmt.Sprintf("batch item duplicates batch_items[%d] within the same request", prev))
		} else {
			seenDedupe[dedupeKey] = idx
		}

		manualSKU := strings.TrimSpace(firstNonEmptyString(item.NewSKU, item.PurchaseSKU))
		if manualSKU != "" {
			if prev, ok := seenSKU[manualSKU]; ok {
				addViolation(prefix+".sku_code", "duplicate_batch_sku", fmt.Sprintf("sku %q duplicates batch_items[%d]", manualSKU, prev))
			} else {
				seenSKU[manualSKU] = idx
			}
		}
	}

	if len(violations) > 0 {
		return taskCreateValidationError("batch task validation failed", p, violations...)
	}
	return nil
}

func validateBatchTaskCreateRequest(p CreateTaskParams) *domain.AppError {
	return ValidateBatchTaskCreateRequest(p)
}

func (s *taskService) buildBatchTaskSkuItems(ctx context.Context, p CreateTaskParams) ([]*taskBatchItemBuild, *domain.AppError) {
	items := make([]*taskBatchItemBuild, 0, len(p.BatchItems))
	seenSKU := map[string]int{}
	for idx, rawItem := range p.BatchItems {
		if p.TaskType == domain.TaskTypeNewProductDevelopment {
			rawItem.ProductShortName = defaultBatchItemProductShortName(rawItem)
			rawItem.CategoryCode = defaultBatchItemCategoryCode(p, rawItem)
		}
		dedupeKey, appErr := computeTaskBatchItemDedupeKey(p.TaskType, rawItem)
		if appErr != nil {
			return nil, taskCreateValidationError(
				"batch task validation failed",
				p,
				taskCreateViolation(fmt.Sprintf("batch_items[%d].variant_json", idx), "invalid_variant_json", appErr.Message),
			)
		}
		variantJSON, appErr := normalizeVariantJSONForTaskBatchItem(rawItem.VariantJSON)
		if appErr != nil {
			return nil, taskCreateValidationError(
				"batch task validation failed",
				p,
				taskCreateViolation(fmt.Sprintf("batch_items[%d].variant_json", idx), "invalid_variant_json", appErr.Message),
			)
		}
		variantJSON, appErr = mergeBatchItemProductIIDIntoVariantJSON(variantJSON, rawItem.ProductIID)
		if appErr != nil {
			return nil, taskCreateValidationError(
				"batch task validation failed",
				p,
				taskCreateViolation(fmt.Sprintf("batch_items[%d].variant_json", idx), "invalid_variant_json", appErr.Message),
			)
		}

		skuCode, autoGenerated, appErr := s.generateOrReserveSkuForBatchItem(ctx, p.TaskType, rawItem)
		if appErr != nil {
			return nil, appErr
		}
		if prev, ok := seenSKU[skuCode]; ok {
			return nil, taskCreateValidationError(
				"batch task validation failed",
				p,
				taskCreateViolation(fmt.Sprintf("batch_items[%d].sku_code", idx), "duplicate_batch_sku", fmt.Sprintf("sku %q duplicates batch_items[%d]", skuCode, prev)),
			)
		}
		seenSKU[skuCode] = idx

		item := &domain.TaskSKUItem{
			SequenceNo:          idx + 1,
			SKUCode:             skuCode,
			SKUStatus:           domain.TaskSKUStatusGenerated,
			ProductNameSnapshot: rawItem.ProductName,
			ProductShortName:    defaultBatchItemProductShortName(rawItem),
			ProductIID:          strings.TrimSpace(rawItem.ProductIID),
			CategoryCode:        defaultBatchItemCategoryCode(p, rawItem),
			MaterialMode:        rawItem.MaterialMode,
			CostPriceMode:       rawItem.CostPriceMode,
			Quantity:            cloneInt64Ptr(rawItem.Quantity),
			BaseSalePrice:       cloneFloat64Ptr(rawItem.BaseSalePrice),
			DesignRequirement:   rawItem.DesignRequirement,
			VariantJSON:         variantJSON,
			ReferenceFileRefs:   domain.NormalizeReferenceFileRefs(rawItem.ReferenceFileRefs),
			DedupeKey:           dedupeKey,
		}
		items = append(items, &taskBatchItemBuild{Item: item, AutoGeneratedSKU: autoGenerated})
	}
	return items, nil
}

func (s *taskService) generateOrReserveSkuForBatchItem(ctx context.Context, taskType domain.TaskType, item CreateTaskBatchSKUItemParams) (string, bool, *domain.AppError) {
	manualSKU := strings.TrimSpace(firstNonEmptyString(item.NewSKU, item.PurchaseSKU))
	if manualSKU != "" {
		existing, err := s.taskRepo.GetSKUItemBySKUCode(ctx, manualSKU)
		if err != nil {
			return "", false, infraError("check batch sku uniqueness", err)
		}
		if existing != nil {
			return "", false, domain.NewAppError(
				domain.ErrCodeInvalidRequest,
				fmt.Sprintf("sku_code %q already exists", manualSKU),
				map[string]interface{}{"sku_code": manualSKU},
			)
		}
		return manualSKU, false, nil
	}

	if supportsDefaultTaskProductCode(taskType) {
		skuCode, appErr := s.generateDefaultTaskProductCode(ctx, taskType, item.CategoryCode)
		if appErr != nil {
			return "", false, appErr
		}
		skuCode = strings.TrimSpace(skuCode)
		if skuCode == "" {
			return "", false, domain.NewAppError(domain.ErrCodeInternalError, "generated sku_code is empty", nil)
		}
		return skuCode, true, nil
	}

	for attempt := 0; attempt < maxBatchSKUGenerateAttempts; attempt++ {
		skuCode, appErr := s.codeRuleSvc.GenerateCode(ctx, domain.CodeRuleTypeNewSKU)
		if appErr != nil {
			return "", false, appErr
		}
		skuCode = strings.TrimSpace(skuCode)
		if skuCode == "" {
			return "", false, domain.NewAppError(domain.ErrCodeInternalError, "generated sku_code is empty", nil)
		}
		existing, err := s.taskRepo.GetSKUItemBySKUCode(ctx, skuCode)
		if err != nil {
			return "", false, infraError("check generated batch sku uniqueness", err)
		}
		if existing == nil {
			return skuCode, true, nil
		}
	}

	return "", false, domain.NewAppError(
		domain.ErrCodeInvalidRequest,
		fmt.Sprintf("failed to generate unique sku for %s", taskType),
		map[string]interface{}{"task_type": taskType},
	)
}

func defaultBatchItemProductShortName(item CreateTaskBatchSKUItemParams) string {
	if value := strings.TrimSpace(item.ProductShortName); value != "" {
		return value
	}
	return strings.TrimSpace(item.ProductName)
}

func defaultBatchItemCategoryCode(p CreateTaskParams, item CreateTaskBatchSKUItemParams) string {
	for _, value := range []string{item.CategoryCode, p.CategoryCode, p.ProductIID, "GENERAL"} {
		if normalized := strings.TrimSpace(value); normalized != "" {
			return normalized
		}
	}
	return "GENERAL"
}

func (s *taskService) createTaskWithBatchSkuItemsTx(ctx context.Context, p CreateTaskParams, task *domain.Task, detail *domain.TaskDetail, items []*taskBatchItemBuild) (int64, error) {
	var newID int64
	var customizationJobID int64
	txErr := s.txRunner.RunInTx(ctx, func(tx repo.Tx) error {
		id, err := s.taskRepo.Create(ctx, tx, task, detail)
		if err != nil {
			return fmt.Errorf("create task: %w", err)
		}
		newID = id
		task.ID = id

		persistedItems := make([]*domain.TaskSKUItem, 0, len(items))
		for _, built := range items {
			if built == nil || built.Item == nil {
				continue
			}
			built.Item.TaskID = id
			persistedItems = append(persistedItems, built.Item)
		}
		if err := s.taskRepo.CreateSKUItems(ctx, tx, persistedItems); err != nil {
			return fmt.Errorf("create task sku items: %w", err)
		}
		if err := s.insertTaskReferenceFileRefFlatRows(ctx, tx, newID, p.ReferenceFileRefs); err != nil {
			return err
		}

		var procurementRecord *domain.ProcurementRecord
		if p.TaskType == domain.TaskTypePurchaseTask {
			if s.procurementRepo == nil {
				return fmt.Errorf("purchase task procurement repo missing")
			}
			procurementRecord = &domain.ProcurementRecord{
				TaskID: newID,
				Status: domain.ProcurementStatusDraft,
			}
			if err := s.procurementRepo.Upsert(ctx, tx, procurementRecord); err != nil {
				return fmt.Errorf("initialize purchase task procurement: %w", err)
			}
			if procurementRecord.ID == 0 {
				return fmt.Errorf("initialize purchase task procurement: missing procurement record id after upsert")
			}
			procurementItems := buildProcurementRecordItemsFromTaskSKUItems(procurementRecord.ID, newID, persistedItems)
			if err := s.procurementRepo.CreateItems(ctx, tx, procurementItems); err != nil {
				return fmt.Errorf("initialize purchase task procurement items: %w", err)
			}
		}
		if task.CustomizationRequired {
			if s.customizationJobRepo == nil {
				return fmt.Errorf("customization job repo missing for customization task")
			}
			job := &domain.CustomizationJob{
				TaskID:       newID,
				DecisionType: domain.CustomizationJobDecisionTypeFinal,
				Status:       domain.CustomizationJobStatusPendingCustomizationReview,
			}
			customizationJobID, err = s.customizationJobRepo.Create(ctx, tx, job)
			if err != nil {
				return fmt.Errorf("create customization job: %w", err)
			}
		}

		eventPayload := map[string]interface{}{
			"creator_id":            p.CreatorID,
			"requester_id":          cloneInt64Ptr(p.RequesterID),
			"operator_group_id":     cloneInt64Ptr(p.OperatorGroupID),
			"owner_department":      task.OwnerDepartment,
			"owner_org_team":        task.OwnerOrgTeam,
			"owner_team":            task.OwnerTeam,
			"priority":              string(task.Priority),
			"deadline_at":           cloneTimePtr(p.DeadlineAt),
			"initial_task_status":   string(task.TaskStatus),
			"demand_text":           detail.DemandText,
			"copy_text":             detail.CopyText,
			"style_keywords":        detail.StyleKeywords,
			"remark":                detail.Remark,
			"note":                  detail.Note,
			"reference_file_refs":   p.ReferenceFileRefs,
			"product_selection":     buildTaskProductSelectionContext(task, detail),
			"procurement_status":    procurementStatusValue(procurementRecord),
			"batch_mode":            string(task.BatchMode),
			"batch_item_count":      task.BatchItemCount,
			"primary_sku_code":      task.PrimarySKUCode,
			"is_batch_task":         task.IsBatchTask,
			"sku_generation_status": string(task.SKUGenerationStatus),
			"customization_job_id":  zeroInt64ToNil(customizationJobID),
		}
		if p.DesignerID != nil && p.TaskType != domain.TaskTypePurchaseTask {
			eventPayload["designer_id"] = cloneInt64Ptr(p.DesignerID)
			eventPayload["assigned_at_creation"] = true
		}
		if _, err := s.taskEventRepo.Append(ctx, tx, newID, domain.TaskEventCreated, &p.CreatorID, mergeTaskEventPayload(taskEventBasePayload(task), eventPayload)); err != nil {
			return err
		}
		if s.blueprintRuleEngine != nil {
			if err := s.blueprintRuleEngine.InitTask(ctx, tx, task); err != nil {
				return fmt.Errorf("initialize task modules: %w", err)
			}
		}
		if task.IsBatchTask {
			if _, err := s.taskEventRepo.Append(ctx, tx, newID, domain.TaskEventBatchItemsCreated, &p.CreatorID, mergeTaskEventPayload(taskEventBasePayload(task), map[string]interface{}{
				"task_id":               newID,
				"task_no":               task.TaskNo,
				"batch_mode":            string(task.BatchMode),
				"batch_item_count":      task.BatchItemCount,
				"primary_sku_code":      task.PrimarySKUCode,
				"sku_generation_status": string(task.SKUGenerationStatus),
				"sku_items":             buildTaskSKUItemEventSummaries(persistedItems),
			})); err != nil {
				return err
			}
		}
		return nil
	})
	if txErr != nil {
		return 0, txErr
	}
	return newID, nil
}

func (s *taskService) insertTaskReferenceFileRefFlatRows(ctx context.Context, tx repo.Tx, taskID int64, refs []domain.ReferenceFileRef) error {
	if s.referenceFileRefFlatRepo == nil || len(refs) == 0 {
		return nil
	}
	normalized := domain.NormalizeReferenceFileRefs(refs)
	for _, ref := range normalized {
		refID := ref.CanonicalID()
		if refID == "" {
			continue
		}
		if _, err := s.referenceFileRefFlatRepo.InsertFlat(ctx, tx, &domain.ReferenceFileRefFlat{
			TaskID:         taskID,
			RefID:          refID,
			OwnerModuleKey: string(domain.ModuleKeyBasicInfo),
			Context:        stringPtr("task_create_reference"),
		}); err != nil {
			return fmt.Errorf("insert task reference_file_ref flat row: %w", err)
		}
	}
	return nil
}

func zeroInt64ToNil(value int64) interface{} {
	if value == 0 {
		return nil
	}
	return value
}

func buildProcurementRecordItemsFromTaskSKUItems(procurementRecordID, taskID int64, items []*domain.TaskSKUItem) []*domain.ProcurementRecordItem {
	if len(items) == 0 {
		return []*domain.ProcurementRecordItem{}
	}
	result := make([]*domain.ProcurementRecordItem, 0, len(items))
	for _, item := range items {
		if item == nil {
			continue
		}
		result = append(result, &domain.ProcurementRecordItem{
			ProcurementRecordID: procurementRecordID,
			TaskID:              taskID,
			TaskSKUItemID:       item.ID,
			SKUCode:             item.SKUCode,
			Status:              domain.ProcurementStatusDraft,
			Quantity:            cloneInt64Ptr(item.Quantity),
			BaseSalePrice:       cloneFloat64Ptr(item.BaseSalePrice),
		})
	}
	return result
}

func buildTaskSKUItemEventSummaries(items []*domain.TaskSKUItem) []map[string]interface{} {
	summaries := make([]map[string]interface{}, 0, len(items))
	for _, item := range items {
		if item == nil {
			continue
		}
		summaries = append(summaries, map[string]interface{}{
			"sequence_no":  item.SequenceNo,
			"sku_code":     item.SKUCode,
			"product_i_id": item.ProductIID,
		})
	}
	return summaries
}

func buildSingleTaskSKUItems(task *domain.Task, detail *domain.TaskDetail) []*taskBatchItemBuild {
	if task == nil || detail == nil {
		return nil
	}
	if task.TaskType != domain.TaskTypeNewProductDevelopment && task.TaskType != domain.TaskTypePurchaseTask {
		return nil
	}
	item := &domain.TaskSKUItem{
		SequenceNo:          1,
		SKUCode:             task.SKUCode,
		SKUStatus:           domain.TaskSKUStatusGenerated,
		ProductNameSnapshot: task.ProductNameSnapshot,
		ProductShortName:    detail.ProductShortName,
		CategoryCode:        detail.CategoryCode,
		MaterialMode:        detail.MaterialMode,
		CostPriceMode:       detail.CostPriceMode,
		Quantity:            cloneInt64Ptr(detail.Quantity),
		BaseSalePrice:       cloneFloat64Ptr(detail.BaseSalePrice),
		DesignRequirement:   detail.DesignRequirement,
		ReferenceFileRefs:   domain.ParseReferenceFileRefsJSON(detail.ReferenceFileRefsJSON),
		DedupeKey:           buildSingleTaskDedupeKey(task, detail),
	}
	if len(item.ReferenceFileRefs) == 0 {
		item.ReferenceFileRefs = domain.ParseReferenceFileRefsJSON(detail.ReferenceImagesJSON)
	}
	if item.ReferenceFileRefs == nil {
		item.ReferenceFileRefs = []domain.ReferenceFileRef{}
	}
	return []*taskBatchItemBuild{{Item: item}}
}

func buildSingleTaskDedupeKey(task *domain.Task, detail *domain.TaskDetail) string {
	sum := sha256.Sum256([]byte(strings.Join([]string{
		string(task.TaskType),
		strings.TrimSpace(task.ProductNameSnapshot),
		strings.TrimSpace(detail.ProductShortName),
		strings.TrimSpace(detail.CategoryCode),
		strings.TrimSpace(detail.MaterialMode),
		strings.TrimSpace(detail.CostPriceMode),
		int64PtrString(detail.Quantity),
	}, "|")))
	return hex.EncodeToString(sum[:])
}

func computeTaskBatchItemDedupeKey(taskType domain.TaskType, item CreateTaskBatchSKUItemParams) (string, *domain.AppError) {
	variantJSON, appErr := normalizeVariantJSONForTaskBatchItem(item.VariantJSON)
	if appErr != nil {
		return "", appErr
	}
	payload := struct {
		TaskType         domain.TaskType `json:"task_type"`
		ProductName      string          `json:"product_name"`
		ProductShortName string          `json:"product_short_name,omitempty"`
		CategoryCode     string          `json:"category_code,omitempty"`
		MaterialMode     string          `json:"material_mode,omitempty"`
		CostPriceMode    string          `json:"cost_price_mode,omitempty"`
		Quantity         *int64          `json:"quantity,omitempty"`
		VariantJSON      string          `json:"variant_json,omitempty"`
	}{
		TaskType:         taskType,
		ProductName:      strings.TrimSpace(item.ProductName),
		ProductShortName: strings.TrimSpace(item.ProductShortName),
		CategoryCode:     strings.TrimSpace(item.CategoryCode),
		MaterialMode:     strings.TrimSpace(item.MaterialMode),
		CostPriceMode:    strings.TrimSpace(item.CostPriceMode),
		Quantity:         cloneInt64Ptr(item.Quantity),
		VariantJSON:      string(variantJSON),
	}
	raw, err := json.Marshal(payload)
	if err != nil {
		return "", domain.NewAppError(domain.ErrCodeInvalidRequest, "failed to normalize batch item dedupe key", nil)
	}
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:]), nil
}

func normalizeVariantJSONForTaskBatchItem(raw json.RawMessage) (json.RawMessage, *domain.AppError) {
	raw = bytes.TrimSpace(raw)
	if len(raw) == 0 || bytes.Equal(raw, []byte("null")) {
		return nil, nil
	}
	var decoded interface{}
	if err := json.Unmarshal(raw, &decoded); err != nil {
		return nil, domain.NewAppError(domain.ErrCodeInvalidRequest, "variant_json must be valid JSON", nil)
	}
	buf := &bytes.Buffer{}
	if err := json.Compact(buf, raw); err != nil {
		return nil, domain.NewAppError(domain.ErrCodeInvalidRequest, "variant_json must be valid JSON", nil)
	}
	return json.RawMessage(buf.Bytes()), nil
}

func mergeBatchItemProductIIDIntoVariantJSON(raw json.RawMessage, productIID string) (json.RawMessage, *domain.AppError) {
	productIID = strings.TrimSpace(productIID)
	if productIID == "" {
		return raw, nil
	}
	obj := map[string]interface{}{}
	if len(bytes.TrimSpace(raw)) > 0 {
		if err := json.Unmarshal(raw, &obj); err != nil {
			return nil, domain.NewAppError(domain.ErrCodeInvalidRequest, "variant_json must be a JSON object when product_i_id is supplied", nil)
		}
	}
	if _, exists := obj["i_id"]; !exists {
		obj["i_id"] = productIID
	}
	if _, exists := obj["product_i_id"]; !exists {
		obj["product_i_id"] = productIID
	}
	encoded, err := json.Marshal(obj)
	if err != nil {
		return nil, domain.NewAppError(domain.ErrCodeInvalidRequest, "variant_json must be valid JSON", nil)
	}
	return json.RawMessage(encoded), nil
}

func int64PtrString(v *int64) string {
	if v == nil {
		return ""
	}
	return fmt.Sprintf("%d", *v)
}
