<template>
 <section class="cost-sync-panel" aria-label="成本同步与冲突">
  <header><div><h2>成本同步</h2><p>人工改价优先。两边不一致时，先确认再同步；不会自动用规则价覆盖人工价。</p></div><button @click="load" :disabled="loading">刷新状态</button></header>
  <p v-if="coverage" class="coverage">同步检查覆盖 {{coverage.tracked}} / {{coverage.total}} 个 SKU · 已回读一致 {{coverage.verified}} · 待确认 {{coverage.conflicts}} · 未报价 {{coverage.unpriced}}。覆盖不代表业务价格已经核定。</p>
  <form @submit.prevent="page=1;load()"><label>查看<select v-model="status" @change="page=1;load()"><option value="conflict">需要确认</option><option value="pending">等待同步</option><option value="retry">等待重试</option><option value="synced">已回读一致</option><option value="baseline">等待首次核对</option><option value="observe">正在核对</option><option value="no_price">未报价</option><option value="">全部状态</option></select></label><label>SKU 编码<input v-model.trim="keyword" placeholder="搜索编码" /></label><button>查询</button></form>
  <p class="hint">页面每 5 秒刷新；ERP 上游仍有拉取延迟。“已回读一致”表示已直接核对 ERP，不只是请求已发送。</p>
  <p v-if="error || decisionError" role="alert">{{decisionError||error}}</p><p v-if="notice" role="status">{{notice}}</p>
  <div class="sync-table"><table><thead><tr><th>SKU</th><th>系统成本</th><th>ERP 成本</th><th>状态 / 最后核对（北京时间）</th><th>处理</th></tr></thead><tbody><tr v-for="row in rows" :key="row.sku_code"><td><strong>{{row.sku_code}}</strong><small v-if="row.manual_lock">{{row.manual_origin==='erp'?'ERP价保护':'人工价保护'}}</small></td><td>{{money(row.local_cost)}}</td><td>{{money(row.erp_cost)}}</td><td>{{labels[row.status]||'待核对'}}<small>{{row.checked_at?new Date(row.checked_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'尚未实时核对'}}</small><small>{{row.reason}}</small></td><td><template v-if="row.status==='conflict'"><button :disabled="!canResolve||row.local_cost==null" @click="choose(row,'local')">保留系统价</button><button :disabled="!canResolve||row.erp_cost==null" @click="choose(row,'erp')">采用 ERP 价</button><small v-if="!canResolve">需要 ERP 管理权限</small></template></td></tr></tbody></table></div>
  <p v-if="!loading&&!rows.length">此范围没有待处理记录。</p>
  <footer><button :disabled="page<=1||loading" @click="page--;load()">上一页</button><span>第 {{page}} 页 · 共 {{total}} 个 SKU</span><button :disabled="page*20>=total||loading" @click="page++;load()">下一页</button></footer>
  <section v-if="selected" class="resolution" role="dialog" aria-label="确认成本选择"><h3>确认 {{selected.sku_code}} 的成本</h3><p>系统 {{money(selected.local_cost)}} · ERP {{money(selected.erp_cost)}}。本次{{choice==='local'?'保留系统价并发送到 ERP':'采用 ERP 价更新系统'}}。</p><label>确认原因<input v-model.trim="reason" maxlength="200" placeholder="请说明选择依据" /></label><p>只处理这一条 SKU。确认期间任何一侧价格变化都会要求重新核对。</p><button :disabled="saving||!reason" @click="resolve">{{saving?'正在确认…':'确认选择'}}</button><button :disabled="saving" @click="selected=null">取消</button></section>
 </section>
</template>
<script setup lang="ts">
import {computed,onMounted,onBeforeUnmount,ref} from 'vue'
import {costManagementApi,type CostSyncState} from '@/services/api/costManagementApi'
import {usePermission} from '@/composables/usePermission'
const permission=usePermission(),canResolve=computed(()=>permission.can('erp.manage'))
const rows=ref<CostSyncState[]>([]),status=ref('conflict'),keyword=ref(''),page=ref(1),total=ref(0),loading=ref(false),error=ref(''),notice=ref(''),saving=ref(false)
const selected=ref<CostSyncState|null>(null),choice=ref<'local'|'erp'>('erp'),reason=ref('')
const decisionError=ref(''),coverage=ref<{total:number;tracked:number;verified:number;conflicts:number;unpriced:number}>()
const labels:Record<string,string>={conflict:'需要确认',pending:'等待 ERP 回读',retry:'稍后重试',synced:'已回读一致',baseline:'等待首次核对',observe:'正在核对',no_price:'未报价'}
let epoch=0,timer:ReturnType<typeof setInterval>|undefined
function money(v:number|null){return v==null?'未确认':`¥${v.toFixed(4).replace(/0+$/,'').replace(/\.$/,'')}`}
async function load(){const ticket=++epoch;loading.value=true;error.value='';try{const result=await costManagementApi.listCostSyncStates({status:status.value||undefined,keyword:keyword.value,page:page.value,page_size:20});if(ticket!==epoch)return;rows.value=result.data||[];total.value=result.pagination.total;coverage.value=result.coverage}catch(e){if(ticket===epoch)error.value=e instanceof Error?e.message:'状态读取失败'}finally{if(ticket===epoch)loading.value=false}}
function choose(row:CostSyncState,side:'local'|'erp'){if(!canResolve.value)return;selected.value={...row};choice.value=side;reason.value='';notice.value='';decisionError.value=''}
async function resolve(){if(!selected.value||!reason.value||saving.value||!canResolve.value)return;saving.value=true;error.value='';try{await costManagementApi.resolveCostSync(selected.value.sku_code,{revision:selected.value.revision,erp_revision:selected.value.erp_revision,choice:choice.value,reason:reason.value});selected.value=null;notice.value='确认已受理。同步完成以 ERP 回读状态为准。';await load()}catch(e){decisionError.value=e instanceof Error?e.message:'确认失败，请刷新核对最新价格';selected.value=null;await load()}finally{saving.value=false}}
onMounted(()=>{load();timer=setInterval(()=>{if(!loading.value&&!saving.value&&!selected.value)load()},5000)})
onBeforeUnmount(()=>{epoch++;if(timer)clearInterval(timer)})
</script>
<style scoped>
.cost-sync-panel{padding:20px;background:rgb(var(--yb-surface));border:1px solid rgb(var(--yb-border));border-radius:12px;min-width:0}.cost-sync-panel header,.cost-sync-panel form,.cost-sync-panel footer{display:flex;gap:12px;align-items:center;justify-content:space-between}.cost-sync-panel h2{font-size:18px}.cost-sync-panel p,.cost-sync-panel small{font-size:12px;color:rgb(var(--yb-text-muted));line-height:1.6}.cost-sync-panel form{justify-content:flex-start;margin:16px 0;align-items:end}.cost-sync-panel label{display:grid;gap:6px;font-size:12px}.cost-sync-panel input,.cost-sync-panel select{padding:9px;border:1px solid rgb(var(--yb-border));border-radius:8px;background:rgb(var(--yb-surface));color:rgb(var(--yb-text))}.cost-sync-panel button{padding:8px 12px;border:1px solid rgb(var(--yb-border));border-radius:8px;color:rgb(var(--yb-brand));background:rgb(var(--yb-surface));cursor:pointer;margin:3px}.cost-sync-panel button:disabled{opacity:.45;cursor:default}.sync-table{overflow:auto}.sync-table table{width:100%;border-collapse:collapse;font-size:13px}.sync-table th,.sync-table td{text-align:left;padding:12px;border-bottom:1px solid rgb(var(--yb-border));vertical-align:top}.sync-table small{display:block;max-width:400px}.resolution{margin-top:16px;padding:16px;border:1px solid rgb(var(--yb-brand));border-radius:10px;background:rgb(var(--yb-brand-soft))}.resolution input{width:min(420px,90%)}.cost-sync-panel footer{margin-top:12px;font-size:12px}@media(max-width:650px){.cost-sync-panel header,.cost-sync-panel form{flex-wrap:wrap}.cost-sync-panel{padding:12px}}
</style>
